# Generated by Django 4.1.4 on 2023-01-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeureuEtatciv',
            fields=[
                ('NumB', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('NumNat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(max_length=20)),
                ('prenom', models.TextField(max_length=20)),
                ('sexe', models.CharField(max_length=5)),
                ('adr', models.TextField(max_length=30)),
                ('proficion', models.TextField(max_length=20)),
                ('etatVie', models.BooleanField()),
                ('etatMaritime', models.TextField(max_length=20)),
                ('NumMere', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumMereC', to='myManager.citoyen')),
                ('NumPere', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.citoyen')),
                ('NumResponssable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NumResponssableC', to='myManager.citoyen')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('NumC', models.AutoField(primary_key=True, serialize=False)),
                ('nomC', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('NumAct', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.TextField(max_length=50)),
                ('domicile', models.TextField(max_length=50)),
                ('existContrat', models.TextField(max_length=50)),
                ('NumCom', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune')),
                ('NumEpouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumEpouse', to='myManager.citoyen')),
                ('NumMare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumMare', to='myManager.citoyen')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('nomP', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Willaya',
            fields=[
                ('NumW', models.AutoField(primary_key=True, serialize=False)),
                ('nomW', models.TextField(max_length=50)),
                ('nomP', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('NumTemoin', models.AutoField(primary_key=True, serialize=False)),
                ('NumActMarr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myManager.marriage')),
                ('NumNat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myManager.citoyen')),
            ],
        ),
        migrations.CreateModel(
            name='Officier',
            fields=[
                ('matoffic', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(max_length=50)),
                ('prenom', models.TextField(max_length=50)),
                ('emploi', models.TextField(max_length=50)),
                ('NumB', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myManager.beureuetatciv')),
            ],
        ),
        migrations.CreateModel(
            name='Naissanse',
            fields=[
                ('NumAct', models.AutoField(primary_key=True, serialize=False)),
                ('dateDeclaration', models.DateTimeField(auto_now=True)),
                ('dateNaise', models.DateField(auto_now=True)),
                ('NumComDec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumComDec', to='myManager.commune')),
                ('NumComNaiss', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NumComNaiss', to='myManager.commune')),
                ('NumNatCon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatConM', to='myManager.citoyen')),
                ('NumNatD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatD', to='myManager.citoyen')),
                ('matOffic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myManager.officier')),
            ],
        ),
        migrations.AddField(
            model_name='marriage',
            name='matOffic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myManager.officier'),
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('NumAct', models.AutoField(primary_key=True, serialize=False)),
                ('hour', models.DecimalField(decimal_places=2, max_digits=2)),
                ('reson', models.TextField(max_length=150)),
                ('NumComDeces', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune')),
                ('NumNatCon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatCon', to='myManager.citoyen')),
                ('NumNatDec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatDec', to='myManager.citoyen')),
                ('NumNatMedecin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatMedecin', to='myManager.citoyen')),
                ('matOffic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.officier')),
            ],
        ),
        migrations.CreateModel(
            name='Daira',
            fields=[
                ('NumD', models.AutoField(primary_key=True, serialize=False)),
                ('nomD', models.TextField(max_length=50)),
                ('NumW', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.willaya')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='NumD',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.daira'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='NumactNaiss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myManager.naissanse'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='comResid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AddField(
            model_name='beureuetatciv',
            name='MatM',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MatM', to='myManager.officier'),
        ),
        migrations.AddField(
            model_name='beureuetatciv',
            name='MatT',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MatT', to='myManager.officier'),
        ),
        migrations.AddField(
            model_name='beureuetatciv',
            name='NimCom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
    ]
