# Generated by Django 4.1.4 on 2023-01-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='NumMere',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumMereC', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='NumPere',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='NumResponssable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NumResponssableC', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='NumactNaiss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myManager.naissanse'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='comResid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='NumComDeces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='NumCom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='NumComNaiss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NumComNaiss', to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='officier',
            name='NumB',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myManager.beureuetatciv'),
        ),
    ]
