# Generated by Django 4.1.4 on 2023-01-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0003_officier_system_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registre_naissance',
            fields=[
                ('annee', models.IntegerField(primary_key=True, serialize=False)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Registre_marriage',
            fields=[
                ('annee', models.IntegerField(primary_key=True, serialize=False)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Registre_deces',
            fields=[
                ('annee', models.IntegerField(primary_key=True, serialize=False)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune')),
            ],
        ),
        migrations.AddField(
            model_name='deces',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.registre_deces'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.registre_marriage'),
        ),
        migrations.AddField(
            model_name='naissanse',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.registre_naissance'),
        ),
    ]
