# Generated by Django 4.1.4 on 2023-01-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0004_registre_naissance_registre_marriage_registre_deces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naissanse',
            old_name='dateNaise',
            new_name='dateNaiss',
        ),
        migrations.AddField(
            model_name='officier',
            name='datePrisService',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='beureuetatciv',
            name='MatM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MatM', to='myManager.officier'),
        ),
        migrations.AlterField(
            model_name='beureuetatciv',
            name='MatT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MatT', to='myManager.officier'),
        ),
        migrations.AlterField(
            model_name='beureuetatciv',
            name='NimCom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='NumMere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumMereC', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='NumPere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='NumResponssable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NumResponssableC', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='comResid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='NumD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.daira'),
        ),
        migrations.AlterField(
            model_name='daira',
            name='NumW',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.willaya'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='NumComDeces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='NumNatDec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatDec', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='NumNatMedecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatMedecin', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='matOffic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.officier'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='NumCom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='NumEpouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NumEpouse', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='NumMare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NumMare', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='matOffic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myManager.officier'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='NumComDec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NumComDec', to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='NumComNaiss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NumComNaiss', to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='NumNatD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NumNatD', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='matOffic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myManager.officier'),
        ),
        migrations.AlterField(
            model_name='officier',
            name='NumB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myManager.beureuetatciv'),
        ),
        migrations.AlterField(
            model_name='willaya',
            name='nomP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myManager.pays'),
        ),
    ]
