# Generated by Django 4.1.4 on 2023-01-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0005_rename_datenaise_naissanse_datenaiss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='adr',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='proficion',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='NumComDec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumComDec', to='myManager.commune'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='NumNatCon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumNatConM', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='NumNatD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumNatD', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='naissanse',
            name='matOffic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myManager.officier'),
        ),
    ]
