# Generated by Django 4.1.4 on 2023-01-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0006_alter_citoyen_adr_alter_citoyen_proficion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deces',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='adr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='etatMaritime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='prenom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='proficion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deces',
            name='NumNatDec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumNatDec', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='NumNatMedecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumNatMedecin', to='myManager.citoyen'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='hour',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='deces',
            name='reson',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='domicile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='etat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='existContrat',
            field=models.BooleanField(),
        ),
    ]
