# Generated by Django 4.1.4 on 2023-01-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0007_deces_date_alter_citoyen_adr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='dateM',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='domicile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='matOffic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myManager.officier'),
        ),
    ]
