# Generated by Django 4.1.4 on 2023-01-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0008_marriage_datem_alter_marriage_domicile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nomC',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='daira',
            name='nomD',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deces',
            name='reson',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='officier',
            name='emploi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='officier',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='officier',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nomP',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='willaya',
            name='nomW',
            field=models.CharField(max_length=50),
        ),
    ]
