# Generated by Django 4.1.4 on 2023-01-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0009_alter_commune_nomc_alter_daira_nomd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naissanse',
            name='dateNaiss',
            field=models.DateField(),
        ),
    ]
